// SPM product 이름을 모아놓은 객체

public struct ExternalDependencyName {

    public static let rxSwift = "RxSwift"
    public static let rxCocoa = "RxCocoa"
    public static let rxTest = "RxTest"
    public static let rxBlocking = "RxBlocking"
    public static let swinject = "Swinject"
    public static let swinjectExtension = "SwinjectExtension-Dynamic"
    public static let swinjectDIContainer = "SwinjectDIContainer-Dynamic"
    public static let snapKit = "SnapKit"
    public static let realm = "Realm"
    public static let realmSwift = "RealmSwift"
    public static let rxSwiftSugarDynamic = "RxSwiftSugar-Dynamic"
    public static let extendedUserDefaults = "ExtendedUserDefaults"
    public static let extendedUserDefaultsRxExtension = "ExtendedUserDefaultsRxExtension"
    public static let sfSafeSymbols = "SFSafeSymbols"
    public static let then = "Then"
    public static let toast = "Toast"
    public static let googleSignIn = "GoogleSignIn"
    public static let googleAPIClientForREST_Drive = "GoogleAPIClientForREST_Drive"
    public static let googleAPIClientForRESTCore = "GoogleAPIClientForRESTCore"
    public static let reactorKit = "ReactorKit"
    public static let swiftCollections = "Collections"
    public static let foundationPlus = "FoundationPlus"
    public static let uiKitPlus = "UIKitPlus"
    public static let swiftUIIntrospectDynamic = "SwiftUIIntrospect-Dynamic"
    public static let pinLayout = "PinLayout"
}
