disabled_rules:
    - line_length
    - identifier_name

trailing_whitespace:
    severity: error

trailing_comma:
    severity: error
    mandatory_comma: true

included:
    - Sources/
    - Tests/
    
    - Project.swift
    
    # Equivalent to Tuist/**/*.swift
    - Tuist/*.swift
    - Tuist/ProjectDescriptionHelpers/*.swift
    - Tuist/ProjectDescriptionHelpers/Extensions/*.swift

excluded:
    - Tests/UserDefaultsPlatformUnitTests/UserSettingsRepositoryTests.swift.plist
    - Tests/UserDefaultsPlatformUnitTests/WCUserDefaultsTests.swift.plist
