disabled_rules:
    - line_length

identifier_name:
    min_length:
        warning: 3
        error: 3
    max_length:
        warning: 60
        error: 60

trailing_whitespace:
    severity: error
