disabled_rules:
    - line_length
    - identifier_name

trailing_whitespace:
    severity: error

trailing_comma:
    severity: error
    mandatory_comma: true

included:
    - Sources/

excluded:
    - Tests/
    - Tuist/
