disabled_rules:
    - line_length
    - identifier_name

trailing_whitespace:
    severity: error

trailing_comma:
    severity: error
    mandatory_comma: true

included:
    - Sources/
    - Tests/
    - Project.swift
    - Tuist/Dependencies.swift
    - Tuist/Config.swift
    - Tuist/ProjectDescriptionHelpers/ExternalDependencyName.swift

excluded:
    
